site_name: Online Judge Documentation
theme:
  name: material
  palette:
    primary: teal
nav:
  - Home: index.md
  - Tech Stack: tech-stack.md
  - APIs: apis.md
  - Testing: testing.md
  - Deployment: deployment.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences